import { Michroma } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const michroma = Michroma({ weight: ['400'], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={michroma.className}>{children}</body>
    </html>
  );
}
